language: ruby
rvm:
  - 1.8.7
script: "rake spec"
env:
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=2.7.20
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.6.9
matrix:
  include:
    - rvm: 1.9.3
      env: PUPPET_VERSION=3.0.2
notifications:
  email: false
gemfile: .gemfile
